server {
    listen 3000;
    root  /usr/share/nginx/html;
    index index.html;

    # Todas las rutas que no sean archivos estáticos → index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}